# This workflow setups an environment with python and uv to be able to run check-jsonschema

name: validate-json

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ '*' ]

jobs:
  validate-renovate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          python-version: 3.13
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run check-jsonschema
        run: uvx check-jsonschema --builtin-schema vendor.renovate renovate-default.json .github/renovate.json renovate-lite.json
